# Generated by Django 2.1.3 on 2018-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
